package com.cloud.leasing.bean

import java.io.Serializable
import java.math.BigDecimal

data class DeviceDetailBean(
    val applicableStratum: String,
    val applicableStratumName: Any,
    val assetOwnership: String,
    val beamNum: String,
    val createTime: String,
    val cutterDiam: String,
    val cutterType: String,
    val cutterTypeName: String,
    val deleted: String,
    val deviceArea: String,
    val deviceBrand: String,
    val deviceBrandName: String,
    val deviceCity: String,
    val deviceMainFileUrl: String,
    val deviceModel: String,
    val deviceNo: String,
    val deviceProvince: String,
    val deviceRentStatus: String,
    val deviceResume: String,
    val deviceStatus: String,
    val deviceType: String,
    val deviceTypeName: String,
    val drivingForm: String,
    val drivingPosition: String,
    val drivingPower: String,
    val drivingTorque: String,
    val focusStatus: Int,
    val hingeForm: String,
    val hingeFormName: String?,
    val id: Int,
    val leaseTime: String,
    val matchStatus: String,
    val mileageUsed: String,
    val openingRate: String,
    val outerDiameter: String,
    val propertyOwner: String,
    val propulsiveForce: String,
    val remarks: String,
    val rentDeviceFileList: List<RentDeviceFile>,
    val rentDeviceUserVoList: Any,
    val turningRadius: String,
    val userId: Int,
    val workingDiam: String,
    val minPrice: Double?,
    val maxPrice: Double?
) : Serializable

data class RentDeviceFile(
    val createTime: String,
    val deleteTime: Any,
    val deleted: String,
    val deviceFileType: String,
    val deviceId: Int,
    val fileName: String,
    val filePath: String,
    val fileSize: String,
    val fileSort: Int,
    val fileSuffix: String,
    val fileType: String,
    val id: Int
) : Serializable