package com.cloud.leasing.bean

import java.io.Serializable

data class MineRequireBean(
    val endRow: Int,
    val hasNextPage: Boolean,
    val hasPreviousPage: Boolean,
    val isFirstPage: Boolean,
    val isLastPage: Boolean,
    val list: MutableList<MineRequire>,
    val navigateFirstPage: Int,
    val navigateLastPage: Int,
    val navigatePages: Int,
    val navigatepageNums: List<Int>,
    val nextPage: Int,
    val pageNum: Int,
    val pageSize: Int,
    val pages: Int,
    val prePage: Int,
    val size: Int,
    val startRow: Int,
    val total: Int
) : Serializable

data class MineRequire(
    var id: Int,
    var isSelect: Boolean = false,
    var isVisible: Boolean = false,
    val beamNum: String,
    val corporateName: Any,
    val createTime: String,
    val cutterDiam: String,
    val cutterType: String,
    val cutterTypeName: Any,
    val deleted: String,
    val demandCity: Any,
    val demandFileList: Any,
    val demandNum: Int,
    val demandProvince: Any,
    val deviceBrand: String,
    val deviceBrandName: Any,
    val deviceType: String,
    val deviceTypeName: Any,
    val drivingTorque: String,
    val focusStatus: Any,
    val geologicalInfo: String,
    val geologicalInfoName: Any,
    val isExamine: String,
    val limitedRange: Any,
    val matchStatus: String,
    val mobile: Any,
    val name: Any,
    val openingRate: String,
    val outerDiameter: String,
    val projectLength: Double,
    val projectLocation: String,
    val propulsiveForce: String,
    val province: Any,
    val remarks: String,
    val turningRadius: String,
    val usageTime: String,
    val userId: Int
) : Serializable